### ISSUE TITLE
Playback bar not found!

### ISSUE THREAD

**Issue by clovelt** [BenWithJamInn/spotify-track-trim#1]
Error!
<img width="312" alt="imagen" src="https://github.com/user-attachments/assets/672ad138-20fd-4303-adf7-2f8c9ae2c7a4">

**Comment by BenWithJamInn** [comment]
Ty for reporting. Haven't updated Spotify in a while so new update must have broken it. I'll comment here once I have fixed it.

**Comment by BenWithJamInn** [comment]
@clovelt  Just updated my Spotify and Spicetify to the latest version and everything seems to be working, posted my current versions below. Can you make sure that you are updated or if you are using the Windows Store version?

Spotify `1.2.49.439`
Spicetify: `2.38.4`
